<?php
defined( 'ABSPATH' ) || exit;

add_action(
	'acf/init',
	function () {
		if ( ! function_exists( 'acf_add_local_field_group' ) ) {
			return;
		}

		acf_add_local_field_group(
			array(
				'key'                   => 'group_6985cd1fc1fd0',
				'title'                 => 'Produk - Galeri Gambar',
				'fields'                => array(
					array(
						'key'               => 'field_6985cd1f65848',
						'label'             => 'Media',
						'name'              => 'media',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'block',
						'sub_fields'        => array(
							array(
								'key'               => 'field_6985ceb765849',
								'label'             => 'Gambar Tambahan 1',
								'name'              => 'image_1',
								'aria-label'        => '',
								'type'              => 'image',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'library'           => 'all',
								'min_width'         => '',
								'min_height'        => '',
								'min_size'          => '',
								'max_width'         => '',
								'max_height'        => '',
								'max_size'          => '',
								'mime_types'        => '',
								'allow_in_bindings' => 0,
								'preview_size'      => 'medium',
							),
							array(
								'key'               => 'field_6985cef12de69',
								'label'             => 'Gambar Tambahan 2',
								'name'              => 'image_2',
								'aria-label'        => '',
								'type'              => 'image',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'library'           => 'all',
								'min_width'         => '',
								'min_height'        => '',
								'min_size'          => '',
								'max_width'         => '',
								'max_height'        => '',
								'max_size'          => '',
								'mime_types'        => '',
								'allow_in_bindings' => 0,
								'preview_size'      => 'medium',
							),
							array(
								'key'               => 'field_6985cf032de6a',
								'label'             => 'Gambar Tambahan 3',
								'name'              => 'image_3',
								'aria-label'        => '',
								'type'              => 'image',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'library'           => 'all',
								'min_width'         => '',
								'min_height'        => '',
								'min_size'          => '',
								'max_width'         => '',
								'max_height'        => '',
								'max_size'          => '',
								'mime_types'        => '',
								'allow_in_bindings' => 0,
								'preview_size'      => 'medium',
							),
							array(
								'key'               => 'field_6985cf132f148',
								'label'             => 'Gambar Tambahan 4',
								'name'              => 'image_4',
								'aria-label'        => '',
								'type'              => 'image',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'library'           => 'all',
								'min_width'         => '',
								'min_height'        => '',
								'min_size'          => '',
								'max_width'         => '',
								'max_height'        => '',
								'max_size'          => '',
								'mime_types'        => '',
								'allow_in_bindings' => 0,
								'preview_size'      => 'medium',
							),
							array(
								'key'               => 'field_6985cf182f149',
								'label'             => 'Gambar Tambahan 5',
								'name'              => 'image_5',
								'aria-label'        => '',
								'type'              => 'image',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'library'           => 'all',
								'min_width'         => '',
								'min_height'        => '',
								'min_size'          => '',
								'max_width'         => '',
								'max_height'        => '',
								'max_size'          => '',
								'mime_types'        => '',
								'allow_in_bindings' => 0,
								'preview_size'      => 'medium',
							),
							array(
								'key'               => 'field_6985cf1c2f14a',
								'label'             => 'Gambar Tambahan 6',
								'name'              => 'image_6',
								'aria-label'        => '',
								'type'              => 'image',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'library'           => 'all',
								'min_width'         => '',
								'min_height'        => '',
								'min_size'          => '',
								'max_width'         => '',
								'max_height'        => '',
								'max_size'          => '',
								'mime_types'        => '',
								'allow_in_bindings' => 0,
								'preview_size'      => 'medium',
							),
						),
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'produk',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
				'display_title'         => '',
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_6984659dae590',
				'title'                 => 'Produk - Harga',
				'fields'                => array(
					array(
						'key'               => 'field_6984659d5cae3',
						'label'             => 'Tampilkan Harga',
						'name'              => 'price_display',
						'aria-label'        => '',
						'type'              => 'select',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'choices'           => array(
							'exact' => 'exact',
							'from'  => 'from',
							'quote' => 'quote',
						),
						'default_value'     => false,
						'return_format'     => 'label',
						'multiple'          => 0,
						'allow_null'        => 0,
						'allow_in_bindings' => 0,
						'ui'                => 0,
						'ajax'              => 0,
						'placeholder'       => '',
						'create_options'    => 0,
						'save_options'      => 0,
					),
					array(
						'key'               => 'field_698466ddd4645',
						'label'             => 'Mulai dari',
						'name'              => 'price_from',
						'aria-label'        => '',
						'type'              => 'number',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'min'               => '',
						'max'               => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'step'              => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_698467152e3ea',
						'label'             => 'Tampilkan harga',
						'name'              => 'price_exact',
						'aria-label'        => '',
						'type'              => 'number',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'min'               => '',
						'max'               => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'step'              => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_698467463ad47',
						'label'             => 'Catatan',
						'name'              => 'price_note',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'produk',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
				'display_title'         => '',
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_698460c73342a',
				'title'                 => 'Produk - Hero Settings',
				'fields'                => array(
					array(
						'key'               => 'field_698460c7cb21d',
						'label'             => 'Tampilkan di Hero',
						'name'              => 'hero_highlight',
						'aria-label'        => '',
						'type'              => 'true_false',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'message'           => '',
						'default_value'     => 0,
						'allow_in_bindings' => 0,
						'ui'                => 0,
						'ui_on_text'        => '',
						'ui_off_text'       => '',
					),
					array(
						'key'               => 'field_6984613dcb21e',
						'label'             => 'Urutan Hero',
						'name'              => 'hero_order',
						'aria-label'        => '',
						'type'              => 'number',
						'instructions'      => 'Semakin kecil semakin dulu tampil',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'min'               => '',
						'max'               => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'step'              => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_698461be659e0',
						'label'             => 'Badge/Tagline Hero',
						'name'              => 'hero_badge',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'produk',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
				'display_title'         => '',
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_69846784e28ad',
				'title'                 => 'Produk - Informasi Tambahan',
				'fields'                => array(
					array(
						'key'               => 'field_6984678500ce5',
						'label'             => 'Nomor Izin Edar',
						'name'              => 'distribution_permit_number',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_698467e88134d',
						'label'             => 'Status Izin Edar',
						'name'              => 'distribution_permit_status',
						'aria-label'        => '',
						'type'              => 'select',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'choices'           => array(
							'active: Aktif'         => 'active: Aktif',
							'process: Dalam Proses' => 'process: Dalam Proses',
							'na: N/A'               => 'na: N/A',
						),
						'default_value'     => false,
						'return_format'     => 'label',
						'multiple'          => 0,
						'allow_null'        => 0,
						'allow_in_bindings' => 0,
						'ui'                => 0,
						'ajax'              => 0,
						'placeholder'       => '',
						'create_options'    => 0,
						'save_options'      => 0,
					),
					array(
						'key'               => 'field_6985c0b96541e',
						'label'             => 'Spesifikasi',
						'name'              => 'spec',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'block',
						'sub_fields'        => array(
							array(
								'key'               => 'field_6985c0db6541f',
								'label'             => 'Tabel Spesifikasi (format: Label: Value)',
								'name'              => 'spec_table',
								'aria-label'        => '',
								'type'              => 'textarea',
								'instructions'      => 'Tulis satu baris per item, format: Label: Value
Contoh:
Energi Maks: 250 Joule
Mode: Semi/Full Otomatis
Baterai: Lithium, standby 5 tahun',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'allow_in_bindings' => 0,
								'rows'              => 14,
								'placeholder'       => '',
								'new_lines'         => '',
							),
							array(
								'key'               => 'field_6985c13e65420',
								'label'             => 'Catatan Spesifikasi',
								'name'              => 'spec_note',
								'aria-label'        => '',
								'type'              => 'textarea',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'allow_in_bindings' => 0,
								'rows'              => '',
								'placeholder'       => '',
								'new_lines'         => '',
							),
						),
					),
					array(
						'key'               => 'field_6986922439671',
						'label'             => 'Kondisi Penawaran',
						'name'              => 'offer_terms',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => 'Harga sudah NETTO
Belum termasuk PPN 12%
Belum termasuk ONGKIR
Pengiriman Barang bisa menggunakan Jasa kami atau ekspedisi lain
Pembayaran bisa via transfer atau datang ke kantor kami di jakarta Timur
Untuk Demo barang silahkan datang ke showroom kami di jakarta Timur
Barang Ready Stok (Konfirmasi)',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'rows'              => '',
						'placeholder'       => '',
						'new_lines'         => '',
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'produk',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
				'display_title'         => '',
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_69852d0f15d72',
				'title'                 => 'Produk - Produk Unggulan',
				'fields'                => array(
					array(
						'key'               => 'field_69852d0fae822',
						'label'             => 'Produk Unggulan',
						'name'              => 'is_featured',
						'aria-label'        => '',
						'type'              => 'true_false',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'message'           => '',
						'default_value'     => 0,
						'allow_in_bindings' => 0,
						'ui'                => 0,
						'ui_on_text'        => '',
						'ui_off_text'       => '',
					),
					array(
						'key'               => 'field_69852d516e405',
						'label'             => 'Urutan Produk',
						'name'              => 'featured_order',
						'aria-label'        => '',
						'type'              => 'number',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'min'               => '',
						'max'               => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'step'              => '',
						'prepend'           => '',
						'append'            => '',
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'produk',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
				'display_title'         => '',
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_6985206eeb59c',
				'title'                 => 'Produk Kategori - Gambar',
				'fields'                => array(
					array(
						'key'               => 'field_698520704e623',
						'label'             => 'Featured Image',
						'name'              => 'category_image',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'url',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'allow_in_bindings' => 0,
						'preview_size'      => 'medium',
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'taxonomy',
							'operator' => '==',
							'value'    => 'kategori_produk',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
				'display_title'         => '',
			)
		);
	},
	20
);
